services:
  bridge:
    build: .
    networks:
      - default

  prometheus:
    image: prom/prometheus
    networks:
      - default
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml:ro'
      - './data/prometheus:/prometheus'
    depends_on:
      - bridge

  grafana:
    image: grafana/grafana-oss
    networks:
      - default
    ports:
      - "9772:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/train-data.json
    volumes:
      - './grafana/dashboards:/var/lib/grafana/dashboards:ro'
      - './grafana/provisioning:/etc/grafana/provisioning:ro'
      - './data/grafana:/var/lib/grafana'
    depends_on:
      - bridge
      - prometheus

networks:
  default:
